version: '3'

services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: lotto
      POSTGRES_USER: username
      POSTGRES_PASSWORD: p@ssw0rd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata:
