server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lotto
    username: username
    password: p@ssw0rd

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect